import path from 'node:path';
import { type FileSystem, getCLILogger, type Logger } from '@ingenyus/swarm';
import { findWaspRoot, realFileSystem } from '../../common';

const FEATURE_FILE = 'feature.wasp.ts';
const BARREL_FILE = 'index.wasp.ts';

interface DiscoveredFeature {
  /** Import specifier relative to the barrel, e.g. `./dashboard/feature.wasp`. */
  importPath: string;
  /** Unique identifier alias for the feature's spec, e.g. `dashboardSpec`. */
  alias: string;
}

/**
 * Generates the features barrel (`src/features/index.wasp.ts`).
 *
 * Wasp 0.24 loads the spec by bundling `main.wasp.ts`'s STATIC import graph, so
 * every feature spec must be statically reachable. This barrel statically
 * imports each `feature.wasp.ts`'s exported `spec` and nests them into a single
 * `featureSpecs` array that `main.wasp.ts` includes in `app({ spec: [...] })`.
 *
 * It is regenerated whenever a feature is created or removed, giving Swarm's
 * auto-discovery ergonomics while satisfying static reachability.
 */
export class FeaturesBarrelGenerator {
  constructor(
    protected logger: Logger = getCLILogger(),
    protected fileSystem: FileSystem = realFileSystem
  ) {}

  /**
   * Rewrites `src/features/index.wasp.ts` to reflect the feature spec files
   * currently present under `src/features`.
   */
  regenerate(): void {
    const featuresDir = path.join(
      findWaspRoot(this.fileSystem),
      'src',
      'features'
    );

    if (!this.fileSystem.existsSync(featuresDir)) {
      return;
    }

    const features = this.discoverFeatures(featuresDir);
    const barrelPath = path.join(featuresDir, BARREL_FILE);

    this.fileSystem.writeFileSync(barrelPath, this.render(features));
    this.logger.success(
      `Regenerated features barrel (${features.length} feature${features.length === 1 ? '' : 's'}): ${barrelPath}`
    );
  }

  /**
   * Recursively finds every `feature.wasp.ts` under `src/features` (features can
   * be nested, e.g. `dashboard/features/stats/feature.wasp.ts`).
   */
  private discoverFeatures(featuresDir: string): DiscoveredFeature[] {
    const found: DiscoveredFeature[] = [];

    const walk = (dir: string): void => {
      const entries = this.fileSystem.readdirSync(dir, { withFileTypes: true });

      for (const entry of entries) {
        const fullPath = path.join(dir, entry.name);

        if (entry.isDirectory()) {
          walk(fullPath);
        } else if (entry.isFile() && entry.name === FEATURE_FILE) {
          const relDir = path
            .relative(featuresDir, path.dirname(fullPath))
            .split(path.sep)
            .join('/');

          found.push({
            importPath: `./${relDir}/feature.wasp`,
            alias: this.toAlias(relDir),
          });
        }
      }
    };

    walk(featuresDir);

    // Deterministic, minimal-diff output.
    found.sort((a, b) => a.importPath.localeCompare(b.importPath));

    return found;
  }

  /**
   * Derives a unique, valid-identifier alias from a feature's relative directory
   * path. Nested-feature `features/` segments are dropped so the alias reflects
   * the feature chain: `dashboard/features/stats` -> `dashboardStatsSpec`.
   */
  private toAlias(relDir: string): string {
    const parts = relDir
      .split('/')
      .filter((segment) => segment && segment !== 'features');

    const camel = parts
      .map((segment, index) => {
        const clean = segment.replace(/[^a-zA-Z0-9]/g, '');
        const cased =
          index === 0
            ? clean.charAt(0).toLowerCase() + clean.slice(1)
            : clean.charAt(0).toUpperCase() + clean.slice(1);

        return cased;
      })
      .join('');

    const base = camel || 'feature';
    const safe = /^[a-zA-Z_$]/.test(base) ? base : `_${base}`;

    return `${safe}Spec`;
  }

  private render(features: DiscoveredFeature[]): string {
    const header = [
      '// GENERATED BY SWARM — DO NOT EDIT.',
      '// Regenerated whenever features are added or removed. It statically',
      '// imports every feature spec so Wasp resolves their references, and nests',
      '// them into a single array for `main.wasp.ts` to include in `app({ spec })`.',
      "import type { Spec } from '@wasp.sh/spec';",
    ];

    const imports = features.map(
      (feature) =>
        `import { spec as ${feature.alias} } from '${feature.importPath}';`
    );

    const body =
      features.length === 0
        ? 'export const featureSpecs: Spec = [];'
        : `export const featureSpecs: Spec = [\n${features
            .map((feature) => `  ${feature.alias},`)
            .join('\n')}\n];`;

    return `${[...header, '', ...imports].join('\n')}\n\n${body}\n`;
  }
}
