// GENERATED BY SWARM — DO NOT EDIT.
// Regenerated whenever features are added or removed. It statically
// imports every feature spec so Wasp resolves their references, and nests
// them into a single array for `main.wasp.ts` to include in `app({ spec })`.
import type { Spec } from '@wasp.sh/spec';

import { spec as rootSpec } from './root/feature.wasp';

export const featureSpecs: Spec = [
  rootSpec,
];
